version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
    working_directory: /tmp/jibikifrontend
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - store_artifacts:
          path: ./dist
      - persist_to_workspace:
          root: .
          paths:
            - dist
  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: /tmp/jibikifrontend/dist
      - run:
          name: Delete old files
          command: |
            ssh $SSH_USER@$SSH_HOST "sudo rm /usr/share/nginx/html/* -rf"
      - run:
          name: Upload JibikiFrontend
          command: |
            scp -ra /tmp/jibikifrontend/dist/. $SSH_USER@$SSH_HOST:/usr/share/nginx/html

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master